# Generated by Django 6.0.4 on 2026-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReports',
            fields=[
                ('group_by', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('filter_row_source', models.TextField(blank=True, null=True)),
                ('default', models.IntegerField()),
            ],
            options={
                'db_table': 'sales_reports',
                'managed': False,
            },
        ),
    ]
