# Generated by Django 6.0.4 on 2026-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country_region', models.CharField(blank=True, max_length=50, null=True)),
                ('web_page', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePrivileges',
            fields=[
                ('pk', models.CompositePrimaryKey('employee_id', 'privilege_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee_privileges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country_region', models.CharField(blank=True, max_length=50, null=True)),
                ('web_page', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'privileges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country_region', models.CharField(blank=True, max_length=50, null=True)),
                ('web_page', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country_region', models.CharField(blank=True, max_length=50, null=True)),
                ('web_page', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
    ]
