# Generated by Django 6.0.4 on 2026-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ids', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('list_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('target_level', models.IntegerField(blank=True, null=True)),
                ('quantity_per_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('discontinued', models.IntegerField()),
                ('minimum_reorder_quantity', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
