# Generated by Django 6.0.4 on 2026-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('discount', models.FloatField()),
                ('date_allocated', models.DateTimeField(blank=True, null=True)),
                ('purchase_order_id', models.IntegerField(blank=True, null=True)),
                ('inventory_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetailsStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'order_details_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_address', models.TextField(blank=True, null=True)),
                ('ship_city', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_zip_postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_country_region', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersTaxStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tax_status_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders_tax_status',
                'managed': False,
            },
        ),
    ]
